### ISSUE TITLE
1.9 kid succesfully gone

### ISSUE THREAD

**Issue by SnesLover22** [apersongithub/Eaglercraft-1.12-Project#8]
yeah we got rid of that 1.9.4 kid and we took over the project. I wish you much luck on your journey, and hopefully you wish us luck on ours lol this will be hard, and most likely yours is harder since its a higher version than 1.9

**Comment by Cerealistic** [comment]
Yall finally got rid of that 8 yr old?

**Comment by SnesLover22** [comment]
yep  we got rid of that dude hes gone now

**Comment by SnesLover22** [comment]
you know he even admitted that he photoshopped and challenged me to a photoshop competition lol here was my entry
![image](https://user-images.githubusercontent.com/110874555/226708503-dfedfc39-5a0f-4ff2-9413-828ad545dbe0.png)
