### ISSUE TITLE
Are you guys still 3% done???

### ISSUE THREAD

**Issue by ImmP3rfect** [apersongithub/Eaglercraft-1.12-Project#9]

**Comment by GodModed** [comment]
This is not an issue. If you have any questions feel free to join the discord server. Please close this issue.

**Comment by ImmP3rfect** [comment]
Will Mods be available??

**Comment by apersongithub** [comment]
no

**Comment by apersongithub** [comment]
you can use data packs in 1.12

**Comment by ImmP3rfect** [comment]
what are data packs?

**Comment by ImmP3rfect** [comment]
is this project abandoned

**Comment by ImmP3rfect** [comment]
will this have singleplayer?

**Comment by ant-7802** [comment]
you cannot use data packs in 1.12, this project is fake

**Comment by apersongithub** [comment]
> you cannot use data packs in 1.12, this project is fake

Reread what I said before

**Comment by ImmP3rfect** [comment]
i hope this project is real and not a repeat of 1.9 project

**Comment by Xtendera** [comment]
> i hope this project is real and not a repeat of 1.9 project

I can tell you with certainty that this project isnt fake, but progress seems to have slowed down. It may end up never finishing. I hope they can prove me wrong.

**Comment by DamienB325** [comment]
@ImmP3rfect The only issue is your lake of patience.

**Comment by Xtendera** [comment]
My lake of patience be like
![image](https://github.com/apersongithub/Eaglercraft-1.12-Project/assets/67883305/3c9d29bf-c9c3-464b-86de-86ecae0dc0e1)

**Comment by papi25** [comment]
nawwww
